2024-10-15 16:01:17,711 INFO    MainThread:216367 [wandb_setup.py:_flush():79] Current SDK version is 0.18.3
2024-10-15 16:01:17,711 INFO    MainThread:216367 [wandb_setup.py:_flush():79] Configure stats pid to 216367
2024-10-15 16:01:17,711 INFO    MainThread:216367 [wandb_setup.py:_flush():79] Loading settings from /home/hgj/.config/wandb/settings
2024-10-15 16:01:17,711 INFO    MainThread:216367 [wandb_setup.py:_flush():79] Loading settings from /home/hgj/SDM274/HA-03&04_Classification_and_Logistic_Regression/wandb/settings
2024-10-15 16:01:17,711 INFO    MainThread:216367 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-10-15 16:01:17,712 INFO    MainThread:216367 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-10-15 16:01:17,712 INFO    MainThread:216367 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'HA-03&04_Classification_and_Logistic_Regression/test.py', 'program_abspath': '/home/hgj/SDM274/HA-03&04_Classification_and_Logistic_Regression/test.py', 'program': './test.py'}
2024-10-15 16:01:17,712 INFO    MainThread:216367 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-10-15 16:01:17,712 INFO    MainThread:216367 [wandb_init.py:_log_setup():532] Logging user logs to /home/hgj/SDM274/HA-03&04_Classification_and_Logistic_Regression/wandb/run-20241015_160117-dt2ewr4q/logs/debug.log
2024-10-15 16:01:17,712 INFO    MainThread:216367 [wandb_init.py:_log_setup():533] Logging internal logs to /home/hgj/SDM274/HA-03&04_Classification_and_Logistic_Regression/wandb/run-20241015_160117-dt2ewr4q/logs/debug-internal.log
2024-10-15 16:01:17,712 INFO    MainThread:216367 [wandb_init.py:init():617] calling init triggers
2024-10-15 16:01:17,712 INFO    MainThread:216367 [wandb_init.py:init():624] wandb.init called with sweep_config: {}
config: {}
2024-10-15 16:01:17,712 INFO    MainThread:216367 [wandb_init.py:init():667] starting backend
2024-10-15 16:01:17,712 INFO    MainThread:216367 [wandb_init.py:init():671] sending inform_init request
2024-10-15 16:01:17,714 INFO    MainThread:216367 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-10-15 16:01:17,715 INFO    MainThread:216367 [wandb_init.py:init():684] backend started and connected
2024-10-15 16:01:17,718 INFO    MainThread:216367 [wandb_init.py:init():779] updated telemetry
2024-10-15 16:01:17,725 INFO    MainThread:216367 [wandb_init.py:init():812] communicating run to backend with 90.0 second timeout
2024-10-15 16:02:47,757 ERROR   MainThread:216367 [wandb_init.py:init():838] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-10-15 16:02:47,757 ERROR   MainThread:216367 [wandb_init.py:init():1262] error in wandb.init()
Traceback (most recent call last):
  File "/home/hgj/anaconda3/envs/sdm274/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1252, in init
    return wi.init()
  File "/home/hgj/anaconda3/envs/sdm274/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 844, in init
    raise error
wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-10-15 16:02:48,532 WARNING MsgRouterThr:216367 [router.py:message_loop():77] message_loop has been closed
